# generated by mBlock5 for codey & rocky
# codes make you happy

import haloboard, event
# initialize variables
c = 0
set2 = 0
led = 0
pl = 0

@event.touchpad1_active   //线程1
def on_1_active():
    global c
    haloboard.led.off_all()
    set2 = 0
    led = 0
    pl = 0
    c = set2
    while True:
        c = set2
        if haloboard.touchpad0.is_touched():
            set2 = set2 + 1
            time.sleep(0.3)
            if set2 > 11:
                set2 = 11

            haloboard.led.show_single(set2, 50, 50, 50)

        if haloboard.touchpad3.is_touched():
            time.sleep(0.3)
            haloboard.led.off_single(set2)
            set2 = set2 + -1
            if set2 < 1:
                set2 = 0

        if haloboard.button.is_pressed():
            time.sleep(0.2)
            led = set2
            while not led == 0:
                time.sleep(10)
                haloboard.led.off_single(led)
                led = led + -1
                c = set2

            c = set2
            led = 0
            set2 = 0
            haloboard.stop_other_scripts()
            haloboard.led.off_all()

@event.button_pressed  //线程2 
def on_button_pressed():
    global c
    time.sleep(0.2)
    while not (haloboard.button.is_pressed() and c == 0):
        haloboard.led.show_single(12, 255, 0, 0)
        time.sleep(0.5)
        haloboard.led.off_single(12)
        time.sleep(0.5)

@event.touchpad2_active  //线程3
def on_2_active1():
    global c
    haloboard.led.off_all()
    haloboard.stop_other_scripts()
